language: c
sudo: false

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.4.2 GHCOPTS="-Werror" JOPTS=""
      addons: {apt: {packages: [cabal-install-1.16, ghc-7.4.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.6.3 GHCOPTS="-Werror" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4 GHCOPTS="-Werror" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.1 GHCOPTS="" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.1],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head GHCOPTS="" JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
   - env: CABALVER=head GHCVER=head GHCOPTS="" JOPTS="-j2"

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - export CABAL=cabal-$CABALVER
 - $CABAL --version
 - ghc-pkg check || rm -rf $HOME/.cabal $HOME/.ghc

install:
 - travis_retry $CABAL update
 - |    
   if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
     $CABAL install --constraint=transformers\ installed happy alex
     export PATH=$HOME/.cabal/bin:$PATH
   fi
 - $CABAL install $JOPTS --enable-tests --only-dependencies --force

script:
 - $CABAL configure -v2 --enable-tests
 - $CABAL build $JOPTS --ghc-options=$GHCOPTS
 - $CABAL test
 - $CABAL check

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313ad\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
