language: haskell
before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - travis/cabal-apt-install $mode

install:
  - cabal install packunused packdeps
  - cabal configure -flib-Werror $mode
  - cabal build --ghc-options=-ddump-minimal-imports

script:
  - $script
  - packdeps
  - packunused
  - hlint src --cpp-define HLINT --cpp-include include

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313ad\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
