env:
 - GHCVER=7.0.1 CABALVER=1.16
 - GHCVER=7.0.4 CABALVER=1.16
 - GHCVER=7.2.2 CABALVER=1.16
 - GHCVER=7.4.2 CABALVER=1.16
 - GHCVER=7.6.3 CABALVER=1.16
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head CABALVER=1.22

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=1.22

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - export CABAL=cabal-$CABALVER
 - $CABAL --version

install:
 - travis_retry cabal update
 - travis_retry sudo cabal-install Cabal-$CABALVER
 - $CABAL install --enable-tests --only-dependencies

script:
 - $CABAL configure -v2 --enable-tests
 - $CABAL build
 - $CABAL sdist
 - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      $CABAL install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313ad\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
